name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore server/PersonalContacts.sln
    - name: Build
      run: dotnet build server/PersonalContacts.sln --no-restore
    - name: Test
      run: dotnet test server/PersonalContacts.sln --no-build --verbosity normal

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - run: cd client && npm install
    - run: cd client && npm run build --if-present
